site_name: My Docs
theme:
  name: material
  custom_dir: overrides
extra_css:
  - stylesheets/photoswipe.min.css
  - stylesheets/default-skin.min.css
extra_javascript:
  - javascripts/photoswipe.min.js
  - javascripts/photoswipe-ui-default.min.js
  - javascripts/extra.js